### ISSUE TITLE
How to re-assign checkbox styles to different symbols?

### ISSUE THREAD

**Issue by j-xella** [catppuccin/obsidian#106]
#91 ticket implementation added support for a whole bunch of various checkbox styles to Catppuzzin schemes. Which is great, but it seems that the checkbox style symbols are kind of set in stone now. For example if you need an incomplete task, it should always be a slash `[/]` and nothing else. While I appreciate that a great deal of thought went into chosing the best possible symbols for various states, there can always be situations when this is not what user needs.

Here is my case. I am a long time [neorg](/nvim-neorg/neorg) user. Neorg has similar concepts of various checkbox types. However, in neorg, incomplete task is `[-]`, and cancelled task is `[_]`, which is different from #94. So when I started using the [tasks](/obsidian-tasks-group/obsidian-tasks) plugin, I configured its task states as in neorg, and then created a custom CSS to visualize **MY** cancelled and incomplete tasks accordingly. I am not an CSS expert, but I found some CSS examples here and there, and got something working.

However, it all broke when #94 went live. Suddenly, my incomplete `[-]` tasks started to look like cancelled, and my CSS knowledge was not enough to override it in custom CSS. Also, since Catppuzzin now has support for cancelled tasks, I would like my cancelled task `[_]` to look the part, but not sure how to do it.

Maybe if I started using tasks in Obsidian now, I would use the same state symbols as in #94. However, by now, my vault is full of tasks with my states, and I would rather not change it all. Besides, I would like to keep the same symbols as in neorg - it makes it less confusing to me when switching between systems. Also, generally speaking, the tasks plugin allows configuring task types with any symbols, so there will be people with similar issues like me.

I have a temporary solution. I created a copy of Catppuzzin theme, and there replaced `"-"` with `"_"` (for cancelled), and then `"/"` with `"-"` (for incomplete). The whole diff is here: [tmeme.css.diff.zip](https://github.com/user-attachments/files/18304968/tmeme.css.diff.zip). However, every time an update to the Catppuzzin theme is released, I will have to reapply it :(

It would be great to have a solution that allows:

- Reassigning checkbox style to a different symbol
- Disabling some checkbox styles (so that its original symbol could be assigned for another style)
- Assigning more than one symbol to a certain checkbox style. So that, for example, both `[/]` and `[-]` checkboxes could look the same

Making it configurable in "Style Setting" plugin would be nice, but any solution that would work with existing Catppuzzin theme would do, for example, a sample custom CSS that would perform the above tasks.

**Comment by mbeckrich** [comment]
Sorry about this! I won’t be back at my computer for a couple hours, but I have a potential solution. I will test it on my machine tonight and update you as soon as I have something working. Don’t worry—we will get it fixed and keep it from breaking in future updates! :)On Jan 3, 2025, at 6:26 PM, j-xella ***@***.***> wrote:﻿
#91 ticket implementation added support for a whole bunch of various checkbox styles to Catppuzzin schemes. Which is great, but it seems that the checkbox style symbols are kind of set in stone now. For example if you need an incomplete task, it should always be a slash [/] and nothing else. While I appreciate that a great deal of thought went into chosing the best possible symbols for various states, there can always be situations when this is not what user needs.
Here is my case. I am a long time neorg user. Neorg has similar concepts of various checkbox types. However, in neorg, incomplete task is [-], and cancelled task is [_], which is different from #94. So when I started using the tasks plugin, I configured its task states as in neorg, and then created a custom CSS to visualize MY cancelled and incomplete tasks accordingly. I am not an CSS expert, but I found some CSS examples here and there, and got something working.
However, it all broke when #94 went live. Suddenly, my incomplete [-] tasks started to look like cancelled, and my CSS knowledge was not enough to override it in custom CSS. Also, since Catppuzzin now has support for cancelled tasks, I would like my cancelled task [_] to look the part, but not sure how to do it.
Maybe if I started using tasks in Obsidian now, I would use the same state symbols as in #94. However, by now, my vault is full of tasks with my states, and I would rather not change it all. Besides, I would like to keep the same symbols as in neorg - it makes it less confusing to me when switching between systems. Also, generally speaking, the tasks plugin allows configuring task types with any symbols, so there will be people with similar issues like me.
I have a temporary solution. I created a copy of Catppuzzin theme, and there replaced "-" with "_" (for cancelled), and then "/" with "-" (for incomplete). The whole diff is here: tmeme.css.diff.zip. However, every time an update to the Catppuzzin theme is released, I will have to reapply it :(
It would be great to have a solution that allow:

Reassigning checkbox style to a different symbol
Disabling some checkbox styles
Assigning more than one symbol to a certain checkbox style. So that, for example, both [/] and [-] checkboxes could look the same

Making it configurable in "Style Setting" plugin would be nice, but any solution that would work with existing Catppuzzin theme would do, for example, a sample custom CSS that would perform the above tasks.

**Comment by mbeckrich** [comment]
Okay, I have tested a few different potential solutions. Unfortunately, I ran into trouble implementing a Style Settings solution that would allow people to pick their own symbols. It should be doable, but is going to take some time to write everything out and get it working. I don't want your theme to be broken, so, in the meantime, you can try the following. Please let me know if you have any questions about the below steps. I will close your other issue, but leave this one open while I work on the Style Settings compatibility.

1. Go to your Obsidian snippets folder (refer to https://help.obsidian.md/Extending+Obsidian/CSS+snippets if you need more info). From your vault folder, that's `your_vault/.obsidian/snippets`. In the snippets folder, create a .css file named whatever you like. For example, `symbols.css`. (Everything you do in your snippets folder takes precedence over what's in the theme, so it should not break when I update Catppuccin.) 

2. Refer to https://github.com/catppuccin/obsidian/blob/main/scss/vendors/_checklists.scss for the names of each checklist item. You can also use https://minimal.guide/plugins/style-settings for visual reference.

3. From Obsidian Settings -> Appearance, scroll down to "CSS Snippets" and toggle on `symbols.css`. If you don't see the css file here, press the refresh icon.

4. In your post, you mention `[-]` and `[\]`. Changing either of these would use css like the below. `var(--url)` will be the svg of your preferred icon. You can use a tool like https://yoksel.github.io/url-encoder/ to convert your icon and then use the bottom left box to get the correct css. Instead of `background-image:`, we use `-webkit-mask-image:`. 

```css
/* [/] Incomplete */
input[data-task="/"],
li[data-task="/"] > input,
li[data-task="/"] > p > input {
  -webkit-mask-image: var(--url);
}

/* [-] Canceled */
input[data-task="-"],
li[data-task="-"] > input,
li[data-task="-"] > p > input {
  &:checked {
    color:var(--text-faint);
    -webkit-mask-image: var(--url);
  }
```

5. To make `[_]` look like a canceled task (this one is more complicated than most of the others, so I have written it out to be copy and pasted into the snippet), try:

```css
/* [_] Canceled */
input[data-task="_"],
li[data-task="_"] > input,
li[data-task="_"] > p > input {
  --checkbox-marker-color: transparent;

  background-color: var(--text-faint) !important;
  &:checked {
    color:var(--text-faint);
    -webkit-mask-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' class='h-5 w-5' viewBox='0 0 20 20' fill='currentColor'%3E%3Cpath fill-rule='evenodd' d='M3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z' clip-rule='evenodd' /%3E%3C/svg%3E");
  }
}

body:not(.tasks) .markdown-source-view.mod-cm6 .HyperMD-task-line[data-task]:is([data-task="_"]),
body:not(.tasks) .markdown-preview-view ul li[data-task="_"].task-list-item.is-checked,
body:not(.tasks) li[data-task="_"].task-list-item.is-checked  {
  color: var(--text-faint);
  text-decoration:line-through solid var(--text-faint) 1px;
}
```

**Comment by j-xella** [comment]
Thank you @mbeckrich for your response. I have tried following your instructions and created CSS snippet [task_states2.zip](https://github.com/user-attachments/files/18308512/task_states2.zip), which I combined with the current version of Catppuzzin scheme.

Unfortunately, the following code

```md
- [ ] to do
- [-] in progress **not looking right**
- [n] to do - next
- [N] in progress - next **not looking right**
- [_] Cancelled task
- [x] Done task
```
 Looks like this:

![image](https://github.com/user-attachments/assets/61280269-9fb6-4265-b85f-f006bf02a43a)

It seems that at least for me, the settings in Catppuzzin CSS take precedence over my CSS snippet, so `[-]` task looks like cancelled, not like incomplete.

**Comment by j-xella** [comment]
Another question - is there a CSS that would make any non-empty task look like undone TODO?

In my case, I would like `[n]` to look like `[ ]`.

**Comment by mbeckrich** [comment]
I am not sure that the svg is formatted correctly in this section:

```css
/* [-] or [N] Incomplete */
input[data-task="-"],
li[data-task="-"] > input,
li[data-task="-"] > p > input,
input[data-task="N"],
li[data-task="N"] > input,
li[data-task="N"] > p > input {
  /* -webkit-mask-image: none; */
  -webkit-mask-image: url("data:image/svg+xml,%3Csvg viewBox='0 0 14 14' xmlns='http://www.w3.org/2000/svg'%3E%3C/svg%3E");
  margin: 0;
}
```

When I replace it with a test svg of my own, the svg appears correctly in Obsidian, but only in the case of the `[N]`. To make it also apply to the `[-]` item, I have applied `important!`. This is generally not best practice, but it may be necessary here—I thought snippets had precedence over themes, but it does seem like that might not be correct, and using `!important` will overcome some of this.

Using the following css, I can insert an example ? icon without issue:

```css
/* [-] or [N] Incomplete */
input[data-task="-"],
li[data-task="-"] > input,
li[data-task="-"] > p > input,
input[data-task="N"],
li[data-task="N"] > input,
li[data-task="N"] > p > input {
  -webkit-mask-image: url('data:image/svg+xml,%3Csvg xmlns="http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg" width="20" height="20" preserveAspectRatio="xMidYMid meet" viewBox="0 0 16 16"%3E%3Cpath fill="white" fill-rule="evenodd" d="M4.475 5.458c-.284 0-.514-.237-.47-.517C4.28 3.24 5.576 2 7.825 2c2.25 0 3.767 1.36 3.767 3.215c0 1.344-.665 2.288-1.79 2.973c-1.1.659-1.414 1.118-1.414 2.01v.03a.5.5 0 0 1-.5.5h-.77a.5.5 0 0 1-.5-.495l-.003-.2c-.043-1.221.477-2.001 1.645-2.712c1.03-.632 1.397-1.135 1.397-2.028c0-.979-.758-1.698-1.926-1.698c-1.009 0-1.71.529-1.938 1.402c-.066.254-.278.461-.54.461h-.777ZM7.496 14c.622 0 1.095-.474 1.095-1.09c0-.618-.473-1.092-1.095-1.092c-.606 0-1.087.474-1.087 1.091S6.89 14 7.496 14Z"%2F%3E%3C%2Fsvg%3E') !important;
  margin: 0;
}
```

It gives me this result:

<img width="187" alt="image" src="https://github.com/user-attachments/assets/73a2b190-54a6-4a05-82ce-39a455dacb65" />

It might be easier if you show me what task items you want to use and what you want them to look like, and then I can write the snippet out for you and save you some time here. A screenshot of the items is probably all I need to do that. I tried to use the diff in your first post, but wasn't able to translate that to a snippet.

**Comment by j-xella** [comment]
From this:

```md
- [ ] to do
- [-] in progress **not looking right**
- [n] to do - next
- [N] in progress - next **not looking right**
- [_] Cancelled task
- [x] Done task
```

I am trying to achieve something like this:

![image](https://github.com/user-attachments/assets/2b1c9293-cdb5-49de-adfd-f4aaa7726b7b)

Comments: 

1. My incomplete task `[-]` (second item in the list) should look like, well, incomplete task
2. Please ignore the "shades" around items 3 and 4 - I know how to achieve that, it is not the issue
3. My todo-next task `[n]` (third item in the list) should look like todo task `[ ]` (first item)
4. My incomplete-next task `[N]` (4th item in the list) should look like incomplete task
5. My cancelled task `[_]` (5th item in the list) should look like cancelled task

**Comment by mbeckrich** [comment]
Cool, let me know how this looks for you. I have commented each item. Of note, the box-shadows on the glow effect items in your list are left commented out, so that you can adjust them to your preference. This is how it looks on my end.

<img width="359" alt="image" src="https://github.com/user-attachments/assets/fb9ccf61-73ec-437e-9a31-ab80bb653667" />


```css
/**
* 1. Apply styling, using !important to override theme
* 2. Remove - image from box
*/

input[data-task="-"],
li[data-task="-"] > input,
li[data-task="-"] > p > input {
    border-color: transparent !important;
    background-color: rgb(var(--ctp-green)) !important;
    box-shadow: 0 0 0 1px rgb(var(--ctp-green), 40%) !important;
    border-radius: 4px !important;
    -webkit-mask-image: unset !important;
}

/* Remove strikethrough on in-progress checklist text. Selectors taken from inspector tool. */

body:not(.tasks) .markdown-source-view.mod-cm6 .HyperMD-task-line[data-task]:is([data-task="-"]),
body:not(.tasks) .markdown-preview-view ul li[data-task="-"].task-list-item.is-checked,
body:not(.tasks) li[data-task="-"].task-list-item.is-checked {
    color: unset;
    text-decoration: unset;
}

/**
* 1. Apply styling, using !important to override theme
* 2. box-shadow is commented out, but can be uncommented for user-preferred glow effect
* 3. Remove background checkmark image. This is currently invisible due to color, but removing it now will prevent
any issues, should color change.
*/

input[data-task="n"],
li[data-task="n"] > input,
li[data-task="n"] > p > input {
    background-color: transparent !important;
    // box-shadow: 0 0 0 1px rgb(var(--ctp-green), 40%) !important
}

label > input[type=checkbox][data-task="n"]::after {
    background-color: unset;
    -webkit-mask-image: unset;
}

/**
* 1. box-shadow is commented, but can be uncommented for user-preferred glow effect. !important must be used
due to theme selector chain
* 2. Remove background checkmark image
*/

input[data-task="N"],
li[data-task="N"] > input,
li[data-task="N"] > p > input {
    // box-shadow: 0 0 0 1px rgb(var(--ctp-green), 40%) !important;
}

label > [type=checkbox][data-task="N"]::after {
    background-color: unset;
    -webkit-mask-image: unset;
}

/**
* 1. Apply styling, using !important to override theme
* 2. Position and implement background-image
*/

label > [type=checkbox][data-task="_"] {
    box-shadow: 0 0 0 1px var(--text-faint) !important;
    &:checked {
        --checkbox-marker-color: transparent !important;
        background-color: var(--text-faint) !important;
        background-position: 50% 50%;
        background-size: 200% 200%;
        background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='24' height='24' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round' class='lucide lucide-square-x'%3E%3Crect width='18' height='18' x='3' y='3' rx='2' ry='2'/%3E%3Cpath d='m15 9-6 6'/%3E%3Cpath d='m9 9 6 6'/%3E%3C/svg%3E");
    }
}

/* Apply canceled text style to "_" */

body:not(.tasks) .markdown-source-view.mod-cm6 .HyperMD-task-line[data-task]:is([data-task="_"]),
body:not(.tasks) .markdown-preview-view ul li[data-task="_"].task-list-item.is-checked,
body:not(.tasks) li[data-task="_"].task-list-item.is-checked {
    color: var(--text-faint);
    text-decoration: var(--text-faint) 1px solid line-through;
}

/* Apply hover effect to adjusted checklist items */
label > [type=checkbox][data-task="-"],
label > [type=checkbox][data-task="n"],
label > [type=checkbox][data-task="N"],
label > [type=checkbox][data-task="_"] {
    &:hover {
    background-color: rgb(var(--ctp-accent)) !important;
    box-shadow: 0 0 0 1px rgb(var(--ctp-accent), 40%) !important;
    }
}

/**
* 1. Note: The theme uses the following css for default to do boxes, so they will look different from [n] and [N] for
* due to this.
border-color: rgb(var(--ctp-maroon));
    background-color: rgb(var(--ctp-red));
    box-shadow: inset 2px 2px 24px rgb(var(--ctp-mantle)), inset -2px -2px 24px rgb(var(--ctp-mantle));
}
*/
```

**Comment by mbeckrich** [comment]
Going to close this, but feel free to reply if you need anything else.

**Comment by j-xella** [comment]
First, thanks a lot for such a big work done!! Second, sorry for the delay :)

Finally I got to trying your latest CSS suggestion. Generally, it was fantastic, except

- it didn't work well inside callouts, as some selectors were missing.
- I believe `//` comments don't work in CSS. Is it something from preprocessor? Anyway, it was easy to replace them with `/* */`
 
I played with CSS a bit and I think got it working:

![image](https://github.com/user-attachments/assets/2e609ea3-188b-4b23-8796-de5f961f3c81)

Here is my final CSS, in case someone is interested:

```css
/**
* 1. Apply styling, using !important to override theme
* 2. Remove - image from box
*/

input[data-task="-"],
li[data-task="-"] > input,
li[data-task="-"] > p > input {
    border-color: transparent !important;
    background-color: rgb(var(--ctp-green)) !important;
    /* box-shadow: 0 0 0 1px rgb(var(--ctp-green), 40%) !important; */
    border-radius: 4px !important;
    -webkit-mask-image: unset !important;
}

/* Remove strikethrough on in-progress checklist text. Selectors taken from inspector tool. */

body:not(.tasks) .markdown-source-view.mod-cm6 .HyperMD-task-line[data-task]:is([data-task="-"]),
body:not(.tasks) .markdown-preview-view ul li[data-task="-"].task-list-item.is-checked,
body:not(.tasks) li[data-task="-"].task-list-item.is-checked {
    color: unset;
    text-decoration: unset;
}

/**
* 1. Apply styling, using !important to override theme
* 2. box-shadow is commented out, but can be uncommented for user-preferred glow effect
* 3. Remove background checkmark image. This is currently invisible due to color, but removing it now will prevent
any issues, should color change.
*/

input[data-task="n"],
li[data-task="n"] > input,
li[data-task="n"] > p > input {
    background-color: transparent !important;
    /* box-shadow: 0 0 0 1px rgb(var(--ctp-green), 40%) !important  */
}

label > input[type=checkbox][data-task="n"]::after,
li[data-task="n"] > input:checked::after,
li[data-task="n"] > p > input:checked::after {
    background-color: unset;
    -webkit-mask-image: unset;
}

/**
* 1. box-shadow is commented, but can be uncommented for user-preferred glow effect. !important must be used
due to theme selector chain
* 2. Remove background checkmark image
*/

input[data-task="N"],
li[data-task="N"] > input,
li[data-task="N"] > p > input {
    /* box-shadow: 0 0 0 1px rgb(var(--ctp-green), 40%) !important; */
}

label > [type=checkbox][data-task="N"]::after,
li[data-task="N"] > input:checked::after,
li[data-task="N"] > p > input:checked::after {
    background-color: unset;
    -webkit-mask-image: unset;
}

/**
* 1. Apply styling, using !important to override theme
* 2. Position and implement background-image
*/

label > [type=checkbox][data-task="_"],
li[data-task="_"] > input {
    /* box-shadow: 0 0 0 1px var(--text-faint) !important; */
    &:checked {
        --checkbox-marker-color: transparent !important;
        background-color: var(--text-faint) !important;
        background-position: 50% 50%;
        background-size: 200% 200%;
        background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='24' height='24' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round' class='lucide lucide-square-x'%3E%3Crect width='18' height='18' x='3' y='3' rx='2' ry='2'/%3E%3Cpath d='m15 9-6 6'/%3E%3Cpath d='m9 9 6 6'/%3E%3C/svg%3E");
    }
}

/* Apply canceled text style to "_" */

body:not(.tasks) .markdown-source-view.mod-cm6 .HyperMD-task-line[data-task]:is([data-task="_"]),
body:not(.tasks) .markdown-preview-view ul li[data-task="_"].task-list-item.is-checked,
body:not(.tasks) li[data-task="_"].task-list-item.is-checked {
    color: var(--text-faint);
    text-decoration: var(--text-faint) 1px solid line-through;
}

/* Apply hover effect to adjusted checklist items */
label > [type=checkbox][data-task="-"],
li[data-task="-"] > input,
label > [type=checkbox][data-task="n"],
li[data-task="n"] > input,
label > [type=checkbox][data-task="N"],
li[data-task="N"] > input,
label > [type=checkbox][data-task="_"],
li[data-task="_"] > input {
    &:hover {
    background-color: rgb(var(--ctp-accent)) !important;
    /* box-shadow: 0 0 0 1px rgb(var(--ctp-accent), 40%) !important; */
    }
}

/**
* 1. Note: The theme uses the following css for default to do boxes, so they will look different from [n] and [N] for
* due to this.
border-color: rgb(var(--ctp-maroon));
    background-color: rgb(var(--ctp-red));
    box-shadow: inset 2px 2px 24px rgb(var(--ctp-mantle)), inset -2px -2px 24px rgb(var(--ctp-mantle));
}
*/

/* special marker for "next" task states - yellow halo */
.task-list-item-checkbox[data-task="n"],
li[data-task="n"] > p > input,
li[data-task="n"] > input,  /* task inside callout */
.task-list-item-checkbox[data-task="N"],
li[data-task="N"] > p > input,
li[data-task="N"] > input {
    box-shadow: 0 0 5px 4px rgb(var(--ctp-green), 40%) !important;
}
```
