### ISSUE TITLE
Conflict with icon folder plugin

### ISSUE THREAD

**Issue by zjuyk** [catppuccin/obsidian#44]
Hi, is there any option to disable default folder icon? It will conflict with https://github.com/FlorianWoelki/obsidian-icon-folder

Please refer https://github.com/FlorianWoelki/obsidian-icon-folder/issues/194

**Comment by mbeckrich** [comment]
I’ll take a look at this tomorrow when I’m back at the computer and give you an update when I know more!On Jun 18, 2023, at 12:33 AM, 千玄子 ***@***.***> wrote:﻿
Hi, is there any option to disable default folder icon? It will conflict with https://github.com/FlorianWoelki/obsidian-icon-folder
Please refer FlorianWoelki/obsidian-icon-folder#194

**Comment by mbeckrich** [comment]
This should be fixed in the most recent update. Thank you for bringing it to my attention! Please reopen the issue if this did not solve your problem. 

The fix will require using the Style Settings plugin (https://github.com/mgmeyers/obsidian-style-settings), if you don't already use it. If you don't want to use the plugin, you can create a snippet (how to: https://help.obsidian.md/Extending+Obsidian/CSS+snippets) with the following css to do the same thing:

```css
  .nav-folder .nav-folder-title .nav-folder-title-content::before,
  .nav-folder.is-collapsed .nav-folder-title .nav-folder-title-content::before,
  .nav-folder .nav-folder-title .nav-folder-title-content::before,
  .nav-folder.is-collapsed .nav-folder-title .nav-folder-title-content::before {
    display: none;
  }
```
