### ISSUE TITLE
Respect folder hierarchy when highlighting tree items

### ISSUE THREAD

**Issue by pedromzadeh** [catppuccin/obsidian#57]
### Description
It would be a huge visual improvement if tree items were highlighted according to the hierarchy they belong to. 

For example, the dropdown lines respect the hierarchy:
![IMG_0062](https://github.com/catppuccin/obsidian/assets/39744455/5f3af3b9-5929-450f-8722-d14f84c7829a)

But highlighted items, whether hovering or selected, do not:
![IMG_0064](https://github.com/catppuccin/obsidian/assets/39744455/dd2abd33-18d9-41a3-a72b-39550d9d39bc)

### Improved Behavior
Highlighting tree items, whether hovering or selected, according to the directory hierarchy they belong to.

**Comment by AnubisNekhet** [comment]
I'm afraid this cannot be achieved with CSS due to the usage of `!important` statements in inline styling. For reference:
<img width="235" alt="image" src="https://github.com/catppuccin/obsidian/assets/102488279/2fccea1b-f07b-4522-80e7-7754ccbd4d4e">

**Comment by pedromzadeh** [comment]
Can it not be achieved at all in Obsidian, or just given the constraints of this theme?

I was about to reference the work on AnuPpuccin, and then I realized you’re the developer! I think your handling of the file explorer is pretty good. When rainbow folders are enabled, highlighted items are bounded by hierarchy. And when rainbow isn’t enabled, your boxes do span the whole tree’s width, but you have them opaque so it’s still clear where I am w.r.t the parent directory.

**Comment by mbeckrich** [comment]
If it's being done inline and with an !important declaration, it's both from the app and can't be superseded by the theme. I will look at some ways to better clarify hierarchy and location in the file tree as part of the theme rewrite, though -- thanks for the feedback!

**Comment by wsm6636** [comment]
Can I ask how to change the colour when selected, I want it not to be spread out but to show an outer border

**Comment by mbeckrich** [comment]
I apologize for the delay on this -- I am having some health issues that have left me unable to work for the time-being. I am hoping to get a diagnosis in April and that whatever the cause is has some decent treatment options! Then I will be back to active development here.

> Can I ask how to change the colour when selected, I want it not to be spread out but to show an outer border

If I understand correctly, try snippet something like (this is very hacky, I apologize):

```css
.theme-dark:not(.css-settings-manager) body:not(.is-grabbing) .tree-item-self.is-active:hover, 
.theme-dark:not(.css-settings-manager) .tree-item-self.is-active, 
.theme-light:not(.css-settings-manager) body:not(.is-grabbing) .tree-item-self.is-active:hover, 
.theme-light:not(.css-settings-manager) .tree-item-self.is-active, 
.ctp-full-palette body:not(.is-grabbing) .tree-item-self.is-active:hover, 
.ctp-full-palette .tree-item-self.is-active {
	color: rgb(205, 214, 244); /*ctp-text*/
	background-color: inherit;
	outline: solid 1px rgb(203, 166, 247); /*ctp-mauve*/
}
```

You're going to encounter the issue of the indentation marker. This occurs in the default theme as well, but will be more noticeable here using the colors of Catppuccin. 

<img width="233" alt="image" src="https://github.com/catppuccin/obsidian/assets/88514414/aa189f1a-7ade-4852-8608-e16c0ead2f03">
